### ISSUE TITLE
NLP Newsletter Issue # 5 Translation [Arabic]

### ISSUE THREAD

**Issue by omarsar** [dair-ai/dair-ai.github.io#26]
@SufianDira For tracking Arabic translation of Issue # 5 of NLP Newsletter.

**Comment by SufianDira** [comment]
Hello!

OMG did this take heck a lot of time to translate. Arabic is an old language and translating such new specialized terminology is a nightmare. I finally finished it though and I think I did a good job. Now that I have read every line multiple times I can appreciate how much effort did you put into writing this newsletter. Keep it up man!

The md file is now hopefully ready to publish, I'm not that good with GitHub and I need to go finish some things now, so, I attached the file to this comment and I hope you can do the rest.

As for the writer information here it's:
SufianDira:
  name: Sufian Diraneyya

Hope everything is fine.

Best Regards,
Sufian Diraneyya
[2020-02-28-NLP_Newsletter[AR]_The_Annotated_GPT-2_And_More.md.txt](https://github.com/dair-ai/dair-ai.github.io/files/4267691/2020-02-28-NLP_Newsletter.AR._The_Annotated_GPT-2_And_More.md.txt)

**Comment by SufianDira** [comment]
I just noticed the file I provided is a .txt. But from what I understand md files are just plain text so it's the same. Correct me on that.

**Comment by omarsar** [comment]
Hi @SufianDira, I will take a look shortly and do any fixes that are necessary. I will keep you posted on the progress. Thanks a lot for doing this. It's very exciting to have this in the Arabic language and I am sure your community will appreciate this effort as much as I do. 

BTW, please send me this info so I add your authorship information to this translation. Email me at ellfae@gmail.com. Your avatar/photo would also be nice as well. Thanks.
```
GITHUB_USERNAME:
  name: NAME
  web: PERSONAL_WEBSITE (OPTIONAL)
  bio: SHORT BIO (OPTIONAL)
  twitter: TWITTER_USERNAME (OPTIONAL)
  instagram: INSTAGRAM_USERNAME (OPTIONAL)
  github: GITHUB_USERNAME (OPTIONAL)
```
